[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.intl", "php82Extensions.mbstring"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080}"
